### ISSUE TITLE
package not works

### ISSUE THREAD

**Issue by celestinoxp** [fracpete/fastrandomforest-weka-package#3]
When use forecast tab and choose fastrandomforest show error

![image](https://user-images.githubusercontent.com/41735311/70620529-70285500-1c0f-11ea-8b40-0e78eab28552.png)

**Comment by fracpete** [comment]
It was never tested with the forecast tab, as this is not a core Weka feature. Does your dataset have a numeric class (instead of nominal)?

**Comment by celestinoxp** [comment]
yes I am trying to predict numeric values

**Comment by fracpete** [comment]
The FastRandomForest only works with nominal classes as it stands, unfortunately.
